[package]
name = "re-flora"
version = "0.1.0"
edition = "2021"

[dependencies]

# https://github.com/ash-rs/ash
ash = { version = "0.38", default-features = false, features = [
    "debug",
    "linked",
    "std",
] }

winit = { version = "0.30", features = ["rwh_05"] }
# https://github.com/Traverse-Research/gpu-allocator
gpu-allocator = "0.27"
ash-window = "0.13"
simple_logger = "5.0"
comfy-table = "7.1.3"

log = "0.4.25"
time = "0.3.37"
egui = "0.31.0"
thiserror = "2.0.11"
egui-winit = "0.31.0"
egui_demo_lib = "0.31.0"
shaderc = "0.8.3"


[features]
default = []
no_validation_layer = []
